# Generated by Django 4.2.2 on 2023-08-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.TextField(max_length=250, verbose_name='Resim Başlığı')),
                ('aciklama', models.TextField(max_length=2000, verbose_name='Resim Açıklaması')),
                ('resim', models.FileField(null=True, upload_to='Resimler/', verbose_name='Resim Yükle')),
                ('kategori', models.ManyToManyField(to='secondMain.kategori')),
            ],
        ),
    ]
