# Generated by Django 4.2.2 on 2023-08-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondMain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resim',
            name='resim',
            field=models.FileField(blank=True, null=True, upload_to='Resimler/', verbose_name='Resim Yükle'),
        ),
    ]
